#!/bin/sh

for sname in `ls .`

do
    if [ -d $sname ]; then
        cd $sname;
        result=$(git branch -r | grep $1);

        if [ ! -s $result ]; then
            echo $sname;
        fi
        cd ..;
    fi
done
